FROM nginx

LABEL maintainer="Teddy Fontaine"
LABEL org.opencontainers.image.source https://github.com/tfSheol/Dockerfile-helper

COPY conf/nginx.conf /etc/nginx/nginx.conf
COPY conf/nginx.vh.default.conf /etc/nginx/conf.d/default.conf

WORKDIR /app